# This file was generated by GoReleaser. DO NOT EDIT.
cask "keycloak-cli" do
  version "0.1.5"

  on_macos do
    on_intel do
      url "https://github.com/bcollard/keycloak-cli/releases/download/v#{version}/kc_#{version}_darwin_amd64.tar.gz"
      sha256 "fdad5653002e4c760b7ee0b004315465c01335666dba33373be192312927d4dc"
    end
    on_arm do
      url "https://github.com/bcollard/keycloak-cli/releases/download/v#{version}/kc_#{version}_darwin_arm64.tar.gz"
      sha256 "a3cb36c4acfcda3a15b42c853d5af0a19719370df96bbb98b2a3dbf1e3e79558"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bcollard/keycloak-cli/releases/download/v#{version}/kc_#{version}_linux_amd64.tar.gz"
      sha256 "1d610fd682902302bff369e363ea19aeca9341d01a35abcb1456bf9ac4f4329d"
    end
    on_arm do
      url "https://github.com/bcollard/keycloak-cli/releases/download/v#{version}/kc_#{version}_linux_arm64.tar.gz"
      sha256 "939bde5b5b00307473edac19881cac78d1202b210447078d628700c594312fdf"
    end
  end

  name "keycloak-cli"
  desc "Keycloak CLI — manage realms, users, groups and clients"
  homepage "https://github.com/bcollard/keycloak-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kc"

  # No zap stanza required

end
