# This file was generated by GoReleaser. DO NOT EDIT.
cask "keycloak-cli" do
  version "0.1.3"

  on_macos do
    on_intel do
      url "https://github.com/bcollard/keycloak-cli/releases/download/v#{version}/kc_#{version}_darwin_amd64.tar.gz"
      sha256 "d555106eec3381429f00521d527c99b5957c5f29cbc8a839d842eae08acbed7a"
    end
    on_arm do
      url "https://github.com/bcollard/keycloak-cli/releases/download/v#{version}/kc_#{version}_darwin_arm64.tar.gz"
      sha256 "72be36079712c4b2d2f1cf80daf833453a59d52ebb007835482e14b86a41dee8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bcollard/keycloak-cli/releases/download/v#{version}/kc_#{version}_linux_amd64.tar.gz"
      sha256 "15c5eff0a713475751da038a36c2b0c4f6e1c190d64b08b390cd2354d74465e9"
    end
    on_arm do
      url "https://github.com/bcollard/keycloak-cli/releases/download/v#{version}/kc_#{version}_linux_arm64.tar.gz"
      sha256 "d833faecae3d774f96e6cc7bfead1093cdc673ea9ffea07f7a4168393439124a"
    end
  end

  name "keycloak-cli"
  desc "Keycloak CLI — manage realms, users, groups and clients"
  homepage "https://github.com/bcollard/keycloak-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kc"

  # No zap stanza required

end
