# This file was generated by GoReleaser. DO NOT EDIT.
cask "keycloak-cli" do
  version "0.1.4"

  on_macos do
    on_intel do
      url "https://github.com/bcollard/keycloak-cli/releases/download/v#{version}/kc_#{version}_darwin_amd64.tar.gz"
      sha256 "3a1272f030068e9e47df05719c7c1b9353c09809721f311762a90f8cc05ceb47"
    end
    on_arm do
      url "https://github.com/bcollard/keycloak-cli/releases/download/v#{version}/kc_#{version}_darwin_arm64.tar.gz"
      sha256 "ca0ddaa40454cf0c6199da96a5278f67b51c3295f2ef4dbb50030a6458e790f1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bcollard/keycloak-cli/releases/download/v#{version}/kc_#{version}_linux_amd64.tar.gz"
      sha256 "8e5c8c9488dbaccc39054883668de016273910fcaed03402c1755fe66584c7e3"
    end
    on_arm do
      url "https://github.com/bcollard/keycloak-cli/releases/download/v#{version}/kc_#{version}_linux_arm64.tar.gz"
      sha256 "e1004175a92533daefe497bd47641b2467a19f5b36d0e5946fec186ab07ae270"
    end
  end

  name "keycloak-cli"
  desc "Keycloak CLI — manage realms, users, groups and clients"
  homepage "https://github.com/bcollard/keycloak-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kc"

  # No zap stanza required

end
